### ISSUE TITLE
Trouble testing variantfoldRNA sample commands

### ISSUE THREAD

**Issue by JasonLongCS** [The-Bevilacqua-Lab/variantfoldrna#2]
I am having trouble testing the first sample command included in the wiki section of this repository. I have installed Conda and the variantfoldRNA on a external server. When trying to run the command, it gives me a syntax error located in the chunk.smk file on line 36, stating that the formatted string is not terminated. I am not that familiar with the snakemake pipeline and would appreciate some help resolving this issue. A screenshot of the error is attached. 
![Screenshot 2024-06-17 111511](https://github.com/The-Bevilacqua-Lab/variantfoldrna/assets/123526518/e2153ed2-dc68-44f0-93f3-4a5965d18d04)

**Comment by Kobie-Kirven** [comment]
Hi Jason, 

Thank you for trying out VariantFoldRNA! So I just tried the example with a fresh install on my cluster and I didn't get any errors. It could just be an older bug that I fixed in an updated version of the code (I am working on making a stable release of the pipeline). Could you try re-cloning the repo and re-installing the pipeline? 

Thanks,
Kobie.

**Comment by JasonLongCS** [comment]
Hi Kobie,

I just re-cloned and re-installed the pipeline. The error is the same. Could it be an error with miniConda? Is there any packages or dependencies I am missing? I have only installed base miniConda.

Best,
Jason

**Comment by Kobie-Kirven** [comment]
Hi Jason, 

It could be a problem with conda. Can you try creating a fresh conda environment and make sure python 3.9 is installed:
`conda create -n test_env python=3.9`

Then, activate the conda env and try pip installing the pipeline. Hopefully that works!

Best,
Kobie.

**Comment by Kobie-Kirven** [comment]
Hi Jason, 

Any luck on getting the pipeline to work? I can also Zoom with you sometime to try to help fix the issue if not. 

Best,
Kobie.

**Comment by JasonLongCS** [comment]
Hi Kobie,

Thank you for your advice, it was the conda environment that was the problem. I have got the pipeline to work with the test data now. 

Best, 

Jason

**Comment by MeganSylvia** [comment]
I also had this issue, but once I saw this thread and created a conda environment specify python 3.9 it worked! (Default python in my initial conda environment was 3.12, so maybe that caused issues?)
