### ISSUE TITLE
Temperature option flag not working correctly

### ISSUE THREAD

**Issue by JasonLongCS** [The-Bevilacqua-Lab/variantfoldrna#3]
Hello Kobie, 

I am back with another error, this time the --temperature flag is not parsing correctly, and saying that 10@40 is not a valid float. I have tried parsing with individual integer values and those have worked. The @ separator is not working for me. I have attached an image.  

Best,

Jason
![image](https://github.com/The-Bevilacqua-Lab/variantfoldrna/assets/123526518/95ee2098-a9c4-42a1-9a0c-2721bf0d5765)

**Comment by MeganSylvia** [comment]
I also ran into this issue, have their been any updates?

**Comment by JasonLongCS** [comment]
@MeganSylvia This has not been addressed, but a workaround you can use is simply making a shell script that does the process automatically. It might be a bit slower, but my attempts at debugging it did not work. My script for example transferred each prediction file to a separate folder before removing the result directory and the temp directory. It then ran the pipeline again for a different temperature. There is most definitely a better way to do this, but as I am not that familiar with the program this was the quickest fix I could use. 

If you want to attempt to debug, it is somehow detecting the @ in the middle and interpreting it as a string, and the temperature flag also accepts only floats/ints. It could be not converting properly before a comparison it is making to check if the @ symbol is within the flag checker.

**Comment by MeganSylvia** [comment]
Hi Jason! Thanks for the response and the update. I am not going to attempt to debug this myself, but I am using a work around similar to what you suggested! I was just hoping to save a little on running time.

**Comment by Kobie-Kirven** [comment]
Hi Jason, 

I am very sorry I think I accidentally closed this issue! I fixed the way the temperatures are parsed and it should be working now.

Best,
Kobie.

**Comment by JasonLongCS** [comment]
Hi Kobie, 

I pulled your changes from the github, and I tried reinstalling the pipeline and it started working up until I got this error message:
![image](https://github.com/user-attachments/assets/934ab97f-9e60-478b-a6a0-79de10916d89)

I have the conda environment set to strict channel priority so I am unsure as to what is wrong here. 

Best,

Jason

**Comment by Kobie-Kirven** [comment]
Hi Jason, 

I didn't change anything with AGAT in any of the recent updates so I'm not sure where this error is coming from. Were the conda environments rebuilt after you updated the pipeline? If not, can you try removing the conda environment so it will automatically rebuild? 

Best,
Kobie.

**Comment by JasonLongCS** [comment]
Hi Kobie, 

Might be my error, but I tried running the test without the temperature command and then after running with the temperature command. It seems to work fine now. I am still unsure as to what the error was. 

Thanks,

Jason
